radiusd:
    build: ./toughengine
    privileged: true
    ports:
        - "1812:1823/udp"
        - "1813:1813/udp"
        - "1815:1815"
    environment:
        - TIMEZONE=CST-8
        - API_URL=http://127.0.0.1:1810/api
        - API_KEY=LpWE9AtfDPQ3ufXBS6gJ37WW8TnSF920
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/var/toughwlan:/var/toughwlan

