acagent:
    build: ./toughac
    privileged: true
    ports:
        - "2000:2000/udp"
        - "1819:1819"
    environment:
        - TIMEZONE=CST-8
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/var/toughwlan:/var/toughwlan