acagent:
    image: "index.alauda.cn/toughstruct/toughac"
    ports:
        - "2000:2000/udp"
        - "3799:3799/udp"
        - "1819:1819"
    environment:
        - TIMEZONE=CST-8
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/toughrun/toughac:/var/toughac