portal:
    build: ./toughengine
    privileged: true
    ports:
        - "50100:50100/udp"
        - "1818:1818"
        - "10422:22"
    environment:
        - ROOT_PASSWORD=toughstruct
        - TIMEZONE=CST-8
        - API_URL=http://127.0.0.1:1810/api
        - API_KEY=LpWE9AtfDPQ3ufXBS6gJ37WW8TnSF920
        - SYSLOG_ENABLE=1
        - SYSLOG_SERVER=121.201.15.99
        - SYSLOG_PORT=514
        - SYSLOG_LEVEL=INFO
    restart: always
    volumes:
        - /home/var/toughwlan:/var/toughwlan

